### ISSUE TITLE
Supports streaming?

### ISSUE THREAD

**Issue by agross** [doowb/assemble-push#1]
If I have a streaming loader, could assemble-push support pushing items to downstream consumers while items still being loaded? Right now it seems as even if the loader supports streaming all items need to be loaded before downstream consumers get items pushed towards them.

Background: I have several thousand of objects. I believe the process could be optimized by reading items while starting to write output items. Am I correct?

**Comment by doowb** [comment]
The way `template` and `assemble-push` is setup will not handle this scenario. This would require a different plugin that combines a custom loader and a plugin similar to this.

The default way `template` handles objects that have been loaded is to add them to a cache and do some processing to them. The default loader takes a glob pattern and return an object of `key/value` pairs that are all loaded onto the cache at once. This is done because there are many cases where `template/assemble` need to know information about everything that is being processed at once. (Like all the partials, all the layouts, related links to other pages).

This plugin then just pulls all the templates that are already cached and pushes them into the stream as `vinyl` files.

I think this is a case for a new plugin that can be configured with the custom loader, which does the streaming and sends one item at a time to `template`. Then takes those pieces and pushes them into the main stream like this plugin does. This would require the assumption that templates don't need to reference data/paths to other templates because there is no guarantee that the other templates will exists at that point in time.

**Comment by agross** [comment]
Many thanks for your explanation! I think I understand what you mean by "all data must be available" before starting to assemble. It just seemed to be an easy way to speed up things (not considering IO pressure on my disk). I'll perhaps revisit this feature later when need arises.
